name: Build Unsigned IPA for DNSCloak

on:
  push:
    branches: [main]
  workflow_dispatch:  # Cho phép chạy thủ công từ tab Actions

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          npm install
          npm install --only=dev

      - name: Run Cordova build
        run: npm run build

      - name: Archive iOS project (unsigned)
        run: |
          cd platforms/ios
          xcodebuild -workspace DNSCryptApp.xcworkspace \
                     -scheme DNSCryptApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/DNSCryptApp.xcarchive \
                     archive CODE_SIGNING_ALLOWED=NO

      - name: Export IPA (unsigned)
        run: |
          cd platforms/ios
          xcodebuild -exportArchive \
                     -archivePath build/DNSCryptApp.xcarchive \
                     -exportOptionsPlist ../../exportOptions-unsigned.plist \
                     -exportPath build/ipa

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: dnscloak-unsigned-ipa
          path: platforms/ios/build/ipa/*.ipa
